language: perl
perl:
  - "5.22"

before_install:
  - git clone git://github.com/marmanold/Date-Lectionary-Time
  - cd Date-Lectionary-Time
  - perl Makefile.PL
  - make
  - make install
  - cpanm --quiet --notest --installdeps .
  - rm -R Date-Lectionary-Time
  - cd ..